spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
#    url: jdbc:postgresql://localhost:5432/attendify
    url: jdbc:postgresql://db:5432/attendify
    username: postgres
    password: password
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  info:
    title: Attendify API
    description: API for managing events and participants
    version: 1.0.0
    api-docs: enabled=true
    swagger-ui: enabled=true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    com.attendify: INFO